# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/todo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/todo.proto\x12\x04todo\"\x1d\n\x0bTodoRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\"3\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\x32?\n\x0bTodoService\x12\x30\n\x0bStreamTodos\x12\x11.todo.TodoRequest\x1a\n.todo.Todo\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.todo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TODOREQUEST']._serialized_start=27
  _globals['_TODOREQUEST']._serialized_end=56
  _globals['_TODO']._serialized_start=58
  _globals['_TODO']._serialized_end=109
  _globals['_TODOSERVICE']._serialized_start=111
  _globals['_TODOSERVICE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
